const MenuItems = [
  {
    id: 1,
    // img: "../../assets/images/mezze.jpg",
    imgName: "mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 2,
    // img: "../assets/images/moussaka.jpg",
    imgName: "moussaka.jpg",
    tags: ["vegan", "paleo"],
    meal: "Moussaka",
    calories: 400,
    nutriScore: 92,
    rating: 4.8,
    numberOfReviews: 441,
  },
  {
    id: 3,
    // img: "../assets/images/greek-salad.jpg",
    imgName: "greek-salad.jpg",
    tags: ["vegan", "paleo"],
    meal: "Greek Salad",
    calories: 420,
    nutriScore: 93,
    rating: 4.4,
    numberOfReviews: 378,
  },
  {
    id: 4,
    // img: "../assets/images/paella.jpg",
    imgName: "paella.jpg",
    tags: ["paleo"],
    meal: "Paella",
    calories: 700,
    nutriScore: 98,
    rating: 4.9,
    numberOfReviews: 834,
  },
  {
    id: 5,
    // img: "../assets/images/tapas.jpg",
    imgName: "tapas.jpg",
    // tags: ["healthy"],
    meal: "Tapas",
    calories: 750,
    nutriScore: 78,
    rating: 4.4,
    numberOfReviews: 412,
  },
  {
    id: 6,
    // img: "../assets/images/risotto.jpg",
    imgName: "risotto.jpg",
    tags: ["vegetarian"],
    meal: "Risotto",
    calories: 695,
    nutriScore: 87,
    rating: 4.3,
    numberOfReviews: 613,
  },
];

export default MenuItems;
