const MenuItems = [
  {
    id: 1,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 2,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 3,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 4,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 5,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
  {
    id: 6,
    img: "../../assets/images/mezze.jpg",
    tags: ["vegetarian"],
    meal: "Mezze",
    calories: 650,
    nutriScore: 74,
    rating: 4.9,
    numberOfReviews: 537,
  },
];

export default MenuItems;
